NewsDisplay/NewsDisplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewsDisplay/news/urls.py
from django.urls import path, include
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('section/<sectionName>', views.section, name='section'),
    path('article/<int:articleID>', views.article, name='article'),
    
    path('editor', views.editorLogin, name='editorLogin'),
    path('editor/logout', views.editorLogout, name='editorLogout'),
    path('editor/view', views.editorView, name='editorView'),
    path('editor/section', views.editorSection, name='editorSection'),
    path('editor/section/add', views.editorSectionAdd, name='editorSectionAdd'),
    path('editor/section/remove', views.editorSectionRemove, name='editorSectionRemove'),
    path('editor/article/add', views.editorArticleAdd, name='editorArticleAdd'),
    path('editor/article/edit', views.editorArticleEdit, name='editorArticleEdit'),
    path('editor/article/editview/<articleID>', views.editorArticleEditView, name='editorArticleEditView'),
    path('editor/front', views.editorFrontPage, name='editorFrontPage'),
    path('editor/front/remove', views.editorFrontRemove, name='editorFrontRemove'),
]

NewsDisplay/news/models.py
from django.db import models

# Create your models here.
class Section(models.Model):
    section = models.CharField(max_length=100, unique=True)
    order = models.IntegerField(default=0)

class Article(models.Model):
    last_updated = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=100, unique=False, default='Anonymous')
    section = models.ForeignKey('Section', on_delete=models.CASCADE)
    header = models.CharField(max_length=200, unique=False)
    subheader = models.CharField(max_length=400, unique=False)
    thumbnail = models.ImageField(upload_to='image/thumbnail/', blank=True, null=True)
    body = models.TextField()

    class Meta:
        ordering = ['-last_updated']


class FrontPage(models.Model):
    article = models.OneToOneField('Article', on_delete=models.CASCADE)


class Image(models.Model):
    image = models.ImageField(upload_to='image/')
    article = models.ForeignKey('Article', on_delete=models.CASCADE, blank=True, null=True)

NewsDisplay/news/forms.py
from django import forms
from .models import *

class ArticleUpload(forms.Form):
    section =  forms.ModelChoiceField(queryset=Section.objects.all(), to_field_name='section')
    author = forms.CharField(max_length=100)
    header = forms.CharField(max_length=200)
    subheader = forms.CharField(max_length=400)
    thumbnail = forms.ImageField()
    body = forms.CharField()


class ArticleEdit(forms.Form):
    author = forms.CharField(max_length=100)
    section = forms.ModelChoiceField(queryset=Section.objects.all(), to_field_name='section')
    header = forms.CharField(max_length=200)
    subheader = forms.CharField(max_length=400)
    thumbnail = forms.ImageField(required=False)
    body = forms.CharField()


class FrontAdd(forms.Form):
    article = forms.ModelChoiceField(queryset=Article.objects.all(), to_field_name='id')


class FrontRemove(forms.Form):
    article = forms.ModelMultipleChoiceField(queryset=FrontPage.objects.all(), to_field_name='id')

NewsDisplay/news/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib import messages

from .forms import *
from .models import *


# Create your views here.
def index(request):
    front = FrontPage.objects.all()[:4]
    section = Section.objects.all()

    catag = []
    for s in section:
        a = Article.objects.filter(section=s)[:3]
        if a:
            catag.append({
                'section': s,
                'article': a,
            })

    context = {
        'front': front,
        'catag': catag,
    }
    return render(request, 'news/index.html', context)


def section(request, sectionName):
    try:
        articles = Article.objects.filter(section=Section.objects.get(section=sectionName))[:10]
    except:
        return redirect(reverse('news:index'))

    context = {
        'section': sectionName,
        'articles': articles,
        'articleDisplayNumber': 10,
    }
    return render(request, 'news/section.html', context)


def article(request, articleID):
    try:
        article = Article.objects.get(id=articleID)
    except:
        return redirect(reverse('news:index'))

    return render(request, 'news/article.html', {'article': article})


@require_http_methods(["GET", "POST"])
def editorLogin(request):
    if request.user.is_authenticated:
        return redirect(reverse('news:editorView'))

    if request.method == 'POST':
        # get input
        username = request.POST['username']
        password = request.POST['password']

        # check credential
        user = authenticate(username=username, password=password, is_superuser=True)

        if user is not None:
            login(request, user)
            return redirect(reverse('news:editorView'))
        else:
            messages.add_message(request, messages.ERROR, 'Invalid login!', extra_tags='alert-danger')
            return redirect(reverse('news:editorLogin'))

    else:
        return render(request, 'editor/login.html')


def editorLogout(request):
    logout(request)
    return redirect(reverse('news:editorLogin'))


@login_required(login_url='news:editorLogin')
def editorView(request):
    return render(request, 'editor/index.html')


@require_http_methods(["GET"])
@login_required(login_url='news:editorLogin')
def editorSection(request):
    section = Section.objects.all()
    context = {
        'section': section,
    }
    return render(request, 'editor/section.html', context)


@require_http_methods(["POST"])
@login_required(login_url='news:editorLogin')
def editorSectionAdd(request):
    # get input
    sectionAdd = request.POST['sectionAdd']

    if not sectionAdd:
        messages.add_message(request, messages.ERROR, 'Invalid input', extra_tags='alert-danger')
        return redirect(reverse('news:editorSection'))

    s = Section(section=sectionAdd)
    try:
        s.save()
    except:
        messages.add_message(request, messages.ERROR, 'No duplicate allowed!', extra_tags='alert-danger')
        return redirect(reverse('news:editorSection'))

    messages.add_message(request, messages.SUCCESS, f'Added "{sectionAdd}"', extra_tags='alert-success')
    return redirect(reverse('news:editorSection'))


@require_http_methods(["POST"])
@login_required(login_url='news:editorLogin')
def editorSectionRemove(request):
    # get input
    sectionRemove = request.POST.getlist('sectionRemove[]')

    l = len(sectionRemove)
    if l == 0:
        messages.add_message(request, messages.ERROR, 'Invalid input', extra_tags='alert-danger')
        return redirect(reverse('news:editorSection'))

    for section in sectionRemove:
        Section.objects.all().filter(section=section).delete()

    messages.add_message(request, messages.WARNING, f'Deleted {l} section(s)', extra_tags='alert-warning')
    return redirect(reverse('news:editorSection'))


@require_http_methods(["GET", "POST"])
@login_required(login_url='news:editorLogin')
def editorArticleAdd(request):
    if request.method == 'POST':
        f = ArticleUpload(request.POST, request.FILES)
        if f.is_valid():
            a = Article(
                author=f.cleaned_data['author'],
                section=f.cleaned_data['section'],
                header=f.cleaned_data['header'],
                subheader=f.cleaned_data['subheader'],
                thumbnail=f.cleaned_data['thumbnail'],
                body=f.cleaned_data['body']
            )
            try:
                a.save()
            except:
                messages.add_message(request, messages.ERROR, 'Trouble saving into data table!', extra_tags='alert-danger')
                return redirect(reverse('news:editorArticleAdd'))

            messages.add_message(request, messages.SUCCESS, 'Added article into database!', extra_tags='alert-success')
            return redirect(reverse('news:editorArticleEditView', kwargs={'articleID': a.id}))
        else:
            messages.add_message(request, messages.ERROR, 'Invalid input!', extra_tags='alert-danger')
        return redirect(reverse('news:editorArticleAdd'))
    else:
        section = Section.objects.all()
        context = {
            'section': section,
        }
        return render(request, 'editor/articleAdd.html', context)


@require_http_methods(["GET"])
@login_required(login_url='news:editorLogin')
def editorArticleEdit(request):
    article = Article.objects.all()
    return render(request, 'editor/articleEdit.html', {'article': article})


@require_http_methods(["GET","POST"])
@login_required(login_url='news:editorLogin')
def editorArticleEditView(request, articleID):
    if request.method == 'POST':
        f = ArticleEdit(request.POST, request.FILES)

        if f.is_valid():
            try:
                a = Article.objects.get(id=articleID)
            except:
                messages.add_message(request, messages.ERROR, 'Error getting id', extra_tags='alert-danger')
                return redirect(reverse('news:editorArticleEdit'))

            a.author = f.cleaned_data['author']
            a.header = f.cleaned_data['header']
            a.section = f.cleaned_data['section']
            a.subheader = f.cleaned_data['subheader']
            a.body = f.cleaned_data['body']

            if f.cleaned_data['thumbnail']:
                a.thumbnail.delete()
                a.thumbnail = f.cleaned_data['thumbnail']

            a.save()

        else:
            messages.add_message(request, messages.ERROR, 'Edit failed!', extra_tags='alert-danger')

        return redirect(reverse('news:editorArticleEditView', kwargs={'articleID':articleID}))

    else:
        try:
            article = Article.objects.get(id=articleID)
        except:
            return redirect(reverse('news:editorArticleEdit'))

        section = Section.objects.all()

        return render(request, 'editor/articleEditView.html', {'article': article, 'section': section})


@require_http_methods(["GET","POST"])
@login_required(login_url='news:editorLogin')
def editorFrontPage(request):
    if request.method == 'POST':
        f = FrontAdd(request.POST)

        if f.is_valid():
            fp = FrontPage(
                article=f.cleaned_data['article']
            )
            try:
                fp.save()
            except:
                messages.add_message(request, messages.ERROR, 'No duplicate allowed', extra_tags='alert-danger')
                return redirect(reverse('news:editorFrontPage'))

            messages.add_message(request, messages.SUCCESS, 'Article added to Front.', extra_tags='alert-success')
        else:
            messages.add_message(request, messages.ERROR, 'Invalid input!', extra_tags='alert-danger')

        return redirect(reverse('news:editorFrontPage'))

    else:
        front = FrontPage.objects.all()
        article = Article.objects.all()
        context = {
            'front': front,
            'article': article,
        }
        return render(request, 'editor/frontEdit.html', context)


@require_http_methods(["POST"])
@login_required(login_url='news:editorLogin')
def editorFrontRemove(request):
    f = FrontRemove(request.POST)

    if f.is_valid():
        for q in f.cleaned_data['article']:
            q.delete()
        messages.add_message(request, messages.SUCCESS, 'Removed article(s) from Front.', extra_tags='alert-success')
    else:
        messages.add_message(request, messages.ERROR, 'Error removing article(s) from Front.', extra_tags='alert-danger')

    return redirect(reverse('news:editorFrontPage'))

NewsDisplay/news/templates/editor/articleAdd.html
{% extends 'editor/layout.html' %}

{% block title %}Add/Remove sections{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <h2>Add an article</h2>
            </div>
        </div>
        {% if messages %}
            <div class="row justify-content-center">
                <div class="col-10">
                    {% for message in messages %}
                        <div
                            class="alert {% if message.extra_tags %}{{ message.extra_tags }}{% endif %} my-4"
                            role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <form action="{% url 'news:editorArticleAdd' %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <label for="sectionSelect">
                        <select class="form-control" name="section" id="sectionSelect">
                            <option value="" disabled selected>Choose a section</option>
                            {% for s in section %}
                                <option value="{{ s.section }}">{{ s.section }}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <div class="col">
                    <input type="text" name="author" class="form-control" placeholder="Enter author" maxlength="100" required>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" name="header" placeholder="Enter headline" maxlength="200" required>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <textarea name="subheader" id="" cols="30" rows="3" class="form-control" placeholder="Enter sub-headline" maxlength="400" required></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="image">Upload header image
                        <input type="file" class="form-control-file" accept="image/*" name="thumbnail" id="image" required>
                    </label>
                </div>
                <div class="col">
                    <img src="https://via.placeholder.com/200" alt="" style="height:10rem">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <textarea name="body" id="" cols="30" rows="10" class="form-control" placeholder="Enter body" required></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <button class="btn btn-primary" type="submit">Upload Article</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

NewsDisplay/news/templates/editor/articleEdit.html
{% extends 'editor/layout.html' %}

{% block title %}Add/Remove sections{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <h2>Edit an article</h2>
            </div>
        </div>

        {% if messages %}
            <div class="row justify-content-center">
                <div class="col-10">
                    {% for message in messages %}
                        <div
                            class="alert {% if message.extra_tags %}{{ message.extra_tags }}{% endif %} my-4"
                            role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if article %}
            {% for a in article %}
                <div class="row">
                    <a class="col border" href="{% url 'news:editorArticleEditView' articleID=a.id %}">
                        <div class="row">
                            <div class="col">
                                <img src="{{ a.thumbnail.url }}" alt="{{ a.thumbnail.name }}" height="100" width="100">
                            </div>
                            <div class="col">
                                <span><b>{{ a.section.section }}:</b></span>
                            </div>
                            <div class="col">
                                <span>{{ a.header }}</span>
                            </div>
                            <div class="col">
                                Last updated: {{ a.last_updated|date:'d-m-Y H:i' }}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <div class="row">
                <div class="col text-center">
                    <h3>No article to edit!</h3>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

NewsDisplay/news/templates/editor/articleEditView.html
{% extends 'editor/layout.html' %}

{% block title %}Add/Remove sections{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <h2>Edit view</h2>
            </div>
        </div>

        {% if messages %}
            <div class="row justify-content-center">
                <div class="col-10">
                    {% for message in messages %}
                        <div
                            class="alert {% if message.extra_tags %}{{ message.extra_tags }}{% endif %} my-4"
                            role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <form action="{% url 'news:editorArticleEditView' articleID=article.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h4>Section:</h4>
                    <label for="sectionSelect">
                        <select class="form-control" name="section" id="sectionSelect">
                            {% for s in section %}
                                <option
                                    value="{{ s.section }}"
                                    {% if s.section == article.section.section %}
                                        selected
                                    {% endif %}>
                                    {{ s.section }}
                                </option>
                            {% endfor %}
                        </select>
                    </label>
                </div>

                <div class="col">
                    <h4>Author:</h4>
                    <input type="text" name="author" class="form-control" placeholder="Enter author" value="{{ article.author }}" maxlength="100">
                </div>
            </div>


            <div class="row">
                <div class="col">
                    <h4>Header:</h4>
                    <input name="header" id="header" type="text" class="form-control" value="{{ article.header }}" maxlength="200">
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <h4>Subheader:</h4>
                    <textarea name="subheader" id="" cols="30" rows="3" class="form-control" placeholder="Enter sub-headline" maxlength="400">{{ article.subheader }}</textarea>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <h4>Header image:</h4>
                    <img src="{{ article.thumbnail.url }}" alt="{{ article.thumbnail.name }}" height="300">
                    <label for="image">Change header image
                        <input type="file" class="form-control-file" accept="image/*" name="thumbnail" id="image">
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <h4>Body:</h4>
                    <textarea name="body" id="" cols="30" rows="10" class="form-control" placeholder="Enter body">{{ article.body }}</textarea>
                </div>
            </div>

            <div class="row">
                <div class="col text-center">
                    <button class="btn btn-primary" type="submit">Edit Article</button>
                </div>
            </div>
        </form>

    </div>

{% endblock %}

NewsDisplay/news/templates/editor/frontEdit.html
{% extends 'editor/layout.html' %}

{% block title %}Editor View{% endblock %}

{% block body %}

    <div class="container pt-5">
        {% if messages %}
            <div class="row justify-content-center">
                <div class="col-10">
                    {% for message in messages %}
                        <div
                            class="alert {% if message.extra_tags %}{{ message.extra_tags }}{% endif %} my-4"
                            role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <form action="{% url 'news:editorFrontPage' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <select name="article" class="form-control" id="">
                        {% for a in article %}
                            <option value="{{ a.id }}">Date: {{ a.last_updated|date:'d/m' }} - Sect: {{ a.section.section }} - {{ a.header }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="row my-3 justify-content-center">
                <div class="col-8">
                    <button type="submit" class="btn btn-primary btn-block">Add to front</button>
                </div>
            </div>
        </form>
        <hr>
        <form action="{% url 'news:editorFrontRemove' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                {% for f in front %}
                    <div class="col-12">
                        <input type="checkbox" name="article" value="{{ f.id }}" id="articleSelect-{{ forloop.counter0 }}">
                        <label for="articleSelect-{{ forloop.counter0 }}">
                            <b>{{ f.article.last_updated|date:'d/m' }} - {{ f.article.section.section }}</b>: {{ f.article.header }}
                        </label>
                    </div>
                {% endfor %}
            </div>
            <div class="row justify-content-center my-3">
                <div class="col-8">
                    <button type="submit" class="btn btn-primary btn-block">Remove from front</button>
                </div>
            </div>

        </form>


    </div>

{% endblock %}

NewsDisplay/news/templates/editor/layout.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        {% load static %}
        <link rel="icon" type="image/png" href="{% static '/news/images/favicon.ico' %}"/>
        <link rel="stylesheet" href="{% static '/editor/style.css' %}">

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">LOGO</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news:editorView' %}">Editor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news:editorLogout' %}">Log out</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block body %}{% endblock %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- React JS -->
        <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>

        <!-- Babel JS -->
        <script src="https://unpkg.com/@babel/standalone@7.4.4/babel.min.js"></script>

        {% block script %}{% endblock %}
    </body>
</html>

NewsDisplay/news/templates/editor/login.html
{% extends 'editor/layout.html' %}

{% block title %}Please Log In{% endblock %}

{% block body %}

    <div class="container pt-5">

        <div class="row mb-5">
            <div class="col text-center">
                <h2>Log In</h2>
            </div>
        </div>
        <div class="row justify-content-center my-3">
            <div class="col-11 col-md-6 col-lg-4">
                <form action="{% url 'news:editorLogin' %}" method="POST">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col">
                            <input type="text" class="form-control" name="username" placeholder="Enter username">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <input type="password" class="form-control" name="password" placeholder="Enter password">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-primary btn-block shadow" type="submit">Log in</button>
                        </div>
                    </div>
                </form>

                {% if messages %}
                    {% for message in messages %}
                        <div
                            class="alert {% if message.extra_tags %}{{ message.extra_tags }}{% endif %} my-4" 
                            role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}{% endblock %}

NewsDisplay/news/templates/editor/section.html
{% extends 'editor/layout.html' %}

{% block title %}Add/Remove sections{% endblock %}

{% block body %}

    <div class="container pt-5">
        <div class="row mb-3">
            <div class="col text-center">
                <h3>Add/Remove sections</h3>
            </div>
        </div>

        {% if messages %}
            <div class="row justify-content-center">
                <div class="col-10">
                    {% for message in messages %}
                        <div
                            class="alert {% if message.extra_tags %}{{ message.extra_tags }}{% endif %} my-4"
                            role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row my-3">
            <div class="col">
                <form action="{% url 'news:editorSectionAdd' %}" method="POST">
                    {% csrf_token %}
                    <div class="row my-4 justify-content-center">
                        <div class="col-11 col-md-7 col-lg-4">
                            <input type="text" class="form-control" placeholder="New section" name="sectionAdd" autocomplete="off">
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-8 col-md-4 col-lg-2">
                            <button class="btn btn-primary btn-block" type="submit">Add</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-8">
                <hr>
            </div>
        </div>

        {% if section %}
            <div class="row justify-content-center">
                <div class="col-10 col-md-8">
                    <form action="{% url 'news:editorSectionRemove' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            {% for s in section %}
                                <div class="col-10 col-md-5 {% if forloop.counter|divisibleby:'2' %}ml-md-auto{% else %}mr-md-auto{% endif %}">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="sectionRemove[]" class="custom-control-input" id="section-{{ s.id }}" value="{{ s.section }}">
                                        <label class="custom-control-label" for="section-{{ s.id }}">
                                            {{ s.section }}
                                        </label>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="row justify-content-center my-4">
                            <div class="col-8 col-md-7 col-lg-6 text-center">
                                <button class="btn btn-primary btn-block" type="submit">
                                    Remove
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="col text-center">
                    <h3>No section yet!</h3>
                </div>
            </div>
        {% endif %}

    </div>

{% endblock %}

{% block script %}

{% endblock %}