NewsDisplay/NewsDisplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewsDisplay/news/urls.py
from django.urls import path, include
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('section/<sectionName>', views.section, name='section'),
    path('article/<int:articleID>', views.article, name='article'),
    
    path('editor', views.editorLogin, name='editorLogin'),
    path('editor/logout', views.editorLogout, name='editorLogout'),
    path('editor/view', views.editorView, name='editorView'),
    path('editor/section', views.editorSection, name='editorSection'),
    path('editor/section/add', views.editorSectionAdd, name='editorSectionAdd'),
    path('editor/section/remove', views.editorSectionRemove, name='editorSectionRemove'),
    path('editor/article/add', views.editorArticleAdd, name='editorArticleAdd'),
    path('editor/article/edit', views.editorArticleEdit, name='editorArticleEdit'),
    path('editor/article/editview/<articleID>', views.editorArticleEditView, name='editorArticleEditView'),
    path('editor/front', views.editorFrontPage, name='editorFrontPage'),
    path('editor/front/remove', views.editorFrontRemove, name='editorFrontRemove'),
]

NewsDisplay/news/models.py
from django.db import models

# Create your models here.
class Section(models.Model):
    section = models.CharField(max_length=100, unique=True)
    order = models.IntegerField(default=0)

class Article(models.Model):
    last_updated = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=100, unique=False, default='Anonymous')
    section = models.ForeignKey('Section', on_delete=models.CASCADE)
    header = models.CharField(max_length=200, unique=False)
    subheader = models.CharField(max_length=400, unique=False)
    thumbnail = models.ImageField(upload_to='image/thumbnail/', blank=True, null=True)
    body = models.TextField()

    class Meta:
        ordering = ['-last_updated']


class FrontPage(models.Model):
    article = models.OneToOneField('Article', on_delete=models.CASCADE)


class Image(models.Model):
    image = models.ImageField(upload_to='image/')
    article = models.ForeignKey('Article', on_delete=models.CASCADE, blank=True, null=True)

NewsDisplay/news/forms.py
from django import forms
from .models import *

class ArticleUpload(forms.Form):
    section =  forms.ModelChoiceField(queryset=Section.objects.all(), to_field_name='section')
    author = forms.CharField(max_length=100)
    header = forms.CharField(max_length=200)
    subheader = forms.CharField(max_length=400)
    thumbnail = forms.ImageField()
    body = forms.CharField()


class ArticleEdit(forms.Form):
    author = forms.CharField(max_length=100)
    section = forms.ModelChoiceField(queryset=Section.objects.all(), to_field_name='section')
    header = forms.CharField(max_length=200)
    subheader = forms.CharField(max_length=400)
    thumbnail = forms.ImageField(required=False)
    body = forms.CharField()


class FrontAdd(forms.Form):
    article = forms.ModelChoiceField(queryset=Article.objects.all(), to_field_name='id')


class FrontRemove(forms.Form):
    article = forms.ModelMultipleChoiceField(queryset=FrontPage.objects.all(), to_field_name='id')

NewsDisplay/news/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib import messages

from .forms import *
from .models import *


# Create your views here.
def index(request):
    front = FrontPage.objects.all()[:4]
    section = Section.objects.all()

    catag = []
    for s in section:
        a = Article.objects.filter(section=s)[:3]
        if a:
            catag.append({
                'section': s,
                'article': a,
            })

    context = {
        'front': front,
        'catag': catag,
    }
    return render(request, 'news/index.html', context)


def section(request, sectionName):
    try:
        articles = Article.objects.filter(section=Section.objects.get(section=sectionName))[:10]
    except:
        return redirect(reverse('news:index'))

    context = {
        'section': sectionName,
        'articles': articles,
        'articleDisplayNumber': 10,
    }
    return render(request, 'news/section.html', context)


def article(request, articleID):
    try:
        article = Article.objects.get(id=articleID)
    except:
        return redirect(reverse('news:index'))

    return render(request, 'news/article.html', {'article': article})


@require_http_methods(["GET", "POST"])
def editorLogin(request):
    if request.user.is_authenticated:
        return redirect(reverse('news:editorView'))

    if request.method == 'POST':
        # get input
        username = request.POST['username']
        password = request.POST['password']

        # check credential
        user = authenticate(username=username, password=password, is_superuser=True)

        if user is not None:
            login(request, user)
            return redirect(reverse('news:editorView'))
        else:
            messages.add_message(request, messages.ERROR, 'Invalid login!', extra_tags='alert-danger')
            return redirect(reverse('news:editorLogin'))

    else:
        return render(request, 'editor/login.html')


def editorLogout(request):
    logout(request)
    return redirect(reverse('news:editorLogin'))


@login_required(login_url='news:editorLogin')
def editorView(request):
    return render(request, 'editor/index.html')


@require_http_methods(["GET"])
@login_required(login_url='news:editorLogin')
def editorSection(request):
    section = Section.objects.all()
    context = {
        'section': section,
    }
    return render(request, 'editor/section.html', context)


@require_http_methods(["POST"])
@login_required(login_url='news:editorLogin')
def editorSectionAdd(request):
    # get input
    sectionAdd = request.POST['sectionAdd']

    if not sectionAdd:
        messages.add_message(request, messages.ERROR, 'Invalid input', extra_tags='alert-danger')
        return redirect(reverse('news:editorSection'))

    s = Section(section=sectionAdd)
    try:
        s.save()
    except:
        messages.add_message(request, messages.ERROR, 'No duplicate allowed!', extra_tags='alert-danger')
        return redirect(reverse('news:editorSection'))

    messages.add_message(request, messages.SUCCESS, f'Added "{sectionAdd}"', extra_tags='alert-success')
    return redirect(reverse('news:editorSection'))


@require_http_methods(["POST"])
@login_required(login_url='news:editorLogin')
def editorSectionRemove(request):
    # get input
    sectionRemove = request.POST.getlist('sectionRemove[]')

    l = len(sectionRemove)
    if l == 0:
        messages.add_message(request, messages.ERROR, 'Invalid input', extra_tags='alert-danger')
        return redirect(reverse('news:editorSection'))

    for section in sectionRemove:
        Section.objects.all().filter(section=section).delete()

    messages.add_message(request, messages.WARNING, f'Deleted {l} section(s)', extra_tags='alert-warning')
    return redirect(reverse('news:editorSection'))


@require_http_methods(["GET", "POST"])
@login_required(login_url='news:editorLogin')
def editorArticleAdd(request):
    if request.method == 'POST':
        f = ArticleUpload(request.POST, request.FILES)
        if f.is_valid():
            a = Article(
                author=f.cleaned_data['author'],
                section=f.cleaned_data['section'],
                header=f.cleaned_data['header'],
                subheader=f.cleaned_data['subheader'],
                thumbnail=f.cleaned_data['thumbnail'],
                body=f.cleaned_data['body']
            )
            try:
                a.save()
            except:
                messages.add_message(request, messages.ERROR, 'Trouble saving into data table!', extra_tags='alert-danger')
                return redirect(reverse('news:editorArticleAdd'))

            messages.add_message(request, messages.SUCCESS, 'Added article into database!', extra_tags='alert-success')
            return redirect(reverse('news:editorArticleEditView', kwargs={'articleID': a.id}))
        else:
            messages.add_message(request, messages.ERROR, 'Invalid input!', extra_tags='alert-danger')
        return redirect(reverse('news:editorArticleAdd'))
    else:
        section = Section.objects.all()
        context = {
            'section': section,
        }
        return render(request, 'editor/articleAdd.html', context)


@require_http_methods(["GET"])
@login_required(login_url='news:editorLogin')
def editorArticleEdit(request):
    article = Article.objects.all()
    return render(request, 'editor/articleEdit.html', {'article': article})


@require_http_methods(["GET","POST"])
@login_required(login_url='news:editorLogin')
def editorArticleEditView(request, articleID):
    if request.method == 'POST':
        f = ArticleEdit(request.POST, request.FILES)

        if f.is_valid():
            try:
                a = Article.objects.get(id=articleID)
            except:
                messages.add_message(request, messages.ERROR, 'Error getting id', extra_tags='alert-danger')
                return redirect(reverse('news:editorArticleEdit'))

            a.author = f.cleaned_data['author']
            a.header = f.cleaned_data['header']
            a.section = f.cleaned_data['section']
            a.subheader = f.cleaned_data['subheader']
            a.body = f.cleaned_data['body']

            if f.cleaned_data['thumbnail']:
                a.thumbnail.delete()
                a.thumbnail = f.cleaned_data['thumbnail']

            a.save()

        else:
            messages.add_message(request, messages.ERROR, 'Edit failed!', extra_tags='alert-danger')

        return redirect(reverse('news:editorArticleEditView', kwargs={'articleID':articleID}))

    else:
        try:
            article = Article.objects.get(id=articleID)
        except:
            return redirect(reverse('news:editorArticleEdit'))

        section = Section.objects.all()

        return render(request, 'editor/articleEditView.html', {'article': article, 'section': section})


@require_http_methods(["GET","POST"])
@login_required(login_url='news:editorLogin')
def editorFrontPage(request):
    if request.method == 'POST':
        f = FrontAdd(request.POST)

        if f.is_valid():
            fp = FrontPage(
                article=f.cleaned_data['article']
            )
            try:
                fp.save()
            except:
                messages.add_message(request, messages.ERROR, 'No duplicate allowed', extra_tags='alert-danger')
                return redirect(reverse('news:editorFrontPage'))

            messages.add_message(request, messages.SUCCESS, 'Article added to Front.', extra_tags='alert-success')
        else:
            messages.add_message(request, messages.ERROR, 'Invalid input!', extra_tags='alert-danger')

        return redirect(reverse('news:editorFrontPage'))

    else:
        front = FrontPage.objects.all()
        article = Article.objects.all()
        context = {
            'front': front,
            'article': article,
        }
        return render(request, 'editor/frontEdit.html', context)


@require_http_methods(["POST"])
@login_required(login_url='news:editorLogin')
def editorFrontRemove(request):
    f = FrontRemove(request.POST)

    if f.is_valid():
        for q in f.cleaned_data['article']:
            q.delete()
        messages.add_message(request, messages.SUCCESS, 'Removed article(s) from Front.', extra_tags='alert-success')
    else:
        messages.add_message(request, messages.ERROR, 'Error removing article(s) from Front.', extra_tags='alert-danger')

    return redirect(reverse('news:editorFrontPage'))

NewsDisplay/news/templates/news/article.html
{% extends 'news/layout.html' %}

{% block title %}{{ article.header }}{% endblock %}

{% block body %}

    <div class="container">

        <div class="row justify-content-center">
            <div class="col col-md-11">

                <!-- section name -->
                <div class="row pageArticleSection">
                    <div class="col">
                        <a href="{% url 'news:section' sectionName=article.section.section %}"><span>{{ article.section.section }}</span></a>
                    </div>
                </div>

                <!-- Article header -->
                <div class="row pageArticleHeader">
                    <div class="col">
                        <span>{{ article.header }}</span><br>
                    </div>
                </div>

                <!-- date & author -->
                <div class="row pageArticleDate">
                    <div class="col">
                        <span>Last updated: {{ article.last_updated }}</span><br>
                        <span>Author: {{ article.author }}</span>
                    </div>
                </div>

                <!-- article subheader -->
                <div class="row pageArticleSubheader">
                    <div class="col">
                        <span>{{ article.subheader }}</span>
                    </div>
                </div>

                <!-- article thumbnail -->
                <div class="row pageArticleImg">
                    <img class="col" src="{{ article.thumbnail.url }}" alt="{{ article.header }}">
                </div>


                <div class="row pageArticleBody">
                    <div class="col">
                        <p>{{ article.body }}</p>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock %}

NewsDisplay/news/templates/news/index.html
{% extends 'news/layout.html' %}

{% block title %}News{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">
            <div class="col">

                <!-- Front slogan -->
                <div class="row pageIndexFrontSlogan justify-content-center">
                    <div class="col col-md-9">
                        <span>Lorem ipsum?</span>
                    </div>
                </div>

                <div class="row justify-content-md-center">
                    <!-- container -->
                    <div class="col-12 col-md-9">
                        <div class="row justify-content-md-between">

                            <!-- front column -->
                            <div class="col-12 col-md-6">

                                <!-- Front page image -->
                                <a class="row pageIndexFrontImg" href="{% url 'news:article' articleID=front.0.article.id %}">
                                    <img
                                        class="col"
                                        src="{{ front.0.article.thumbnail.url }}"
                                        alt="{{ front.0.article.header }}">
                                </a>

                                <!-- front page header -->
                                <div class="row pageIndexFrontHeader">
                                    <div class="col">

                                        <a href="{% url 'news:article' articleID=front.0.article.id %}">
                                            <!-- front date -->
                                            <span>{{ front.0.article.last_updated|date:'d/m/y' }}</span><br>

                                            <!-- front header -->
                                            <span>{{ front.0.article.header }}</span>
                                        </a>
                                    </div>
                                </div>

                            </div>

                            <!-- subfront column -->
                            <div class="col-12 col-md-6">

                                {% for f in front %}
                                    {% if forloop.counter0 != 0 %}
                                        <hr class="mt-md-0">

                                        <div class="pageIndexSubHeader">
                                            <a href="{% url 'news:article' articleID=f.article.id %}">
                                                <!-- subfront date -->
                                                <span>{{ f.article.last_updated|date:'d/m/y' }}</span><br>

                                                <!-- subfront header -->
                                                <span>{{ f.article.header }}</span>
                                            </a>
                                        </div>
                                    {% endif %}
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>


                <!-- section -->
                <div class="row justify-content-center">
                    <div class="col-12 col-md-9">
                        <div class="row">
                            {% for c in catag %}
                                <div class="col-12 col-md-6">
                                    <!-- section name -->
                                    <div class="row pageIndexSectionName">
                                        <div class="col">
                                            <a href="{% url 'news:section' sectionName=c.section.section %}"><span>{{ c.section.section }}</span></a>
                                        </div>
                                    </div>

                                    <!-- section header -->
                                    <!-- section header img -->
                                    <a class="row pageIndexSectionImg" href="{% url 'news:article' articleID=c.article.0.id %}">
                                        <img class="col" src="{{ c.article.0.thumbnail.url }}" alt="{{ c.article.0.header }}">
                                    </a>

                                    <!-- section header header -->
                                    <div class="row pageIndexSectionHeader">
                                        <a class="col" href="{% url 'news:article' articleID=c.article.0.id %}">
                                            <!-- date -->
                                            <span>{{ c.article.0.last_updated|date:'d/m/y' }}</span><br>

                                            <!-- header -->
                                            <span>{{ c.article.0.header }}</span>
                                        </a>
                                    </div>

                                    <!-- section subheader -->
                                    {% for a in c.article %}
                                        {% if forloop.counter0 != 0 %}
                                            <div class="row pageIndexSectionSubHeader">
                                                <a class="col" href="{% url 'news:article' articleID=a.id %}">
                                                    <hr>
                                                    <!-- date -->
                                                    <span>{{ a.last_updated|date:'d/m/y' }}</span><br>

                                                    <!-- subheader -->
                                                    <span>{{ a.header }}</span>
                                                </a>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>


            </div>
        </div>


    </div>

{% endblock %}

NewsDisplay/news/templates/news/layout.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        {% load static %}
        <link rel="icon" type="image/png" href="{% static '/news/images/favicon.ico' %}"/>

        <link rel="stylesheet" href="{% static '/news/style.css' %}">

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'news:index' %}">LOGO</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news:index' %}">Front Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">About</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block body %}{% endblock %}

        <footer>
            <p>This web application is a project for the purpose of practise and demonstration.</p>
            <p>Made by Elhemage</p>
        </footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- React JS -->
        <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>

        <!-- Babel JS -->
        <script src="https://unpkg.com/@babel/standalone@7.4.4/babel.min.js"></script>

        {% block script %}{% endblock %}
    </body>
</html>

NewsDisplay/news/templates/news/section.html
{% extends 'news/layout.html' %}

{% block title %}{{ section }}{% endblock %}

{% block body %}

    <div class="container">

        <!-- section name -->
        <div class="row pageSectionBigName justify-content-center">
            <div class="col col-md-7">
                <span>{{ section }}</span>
            </div>
        </div>

        <!-- section articles -->
        {% for a in articles %}
            <div class="row pageSectionArticleContainer">
                <div class="col">

                    <!-- article thumbnail -->
                    <a class="row justify-content-center" href="{% url 'news:article' articleID=a.id %}">
                        <img class="col-12 col-md-7 pageSectionArticleThumbnail" src="{{ a.thumbnail.url }}" alt="{{ a.thumbnail.header }}">
                    </a>

                    <!-- article header -->
                    <div class="row justify-content-center">
                        <a class="col-12 col-md-7 pageSectionArticleHeader" href="{% url 'news:article' articleID=a.id %}">
                            <!-- date -->
                            <span>{{ a.last_updated|date:'d/m/y' }}</span>
                            <br>
                            <!-- header -->
                            <span>{{ a.header }}</span>
                        </a>
                    </div>

                </div>
            </div>
        {% endfor %}

        <!-- show more article buttion -->
        <div class="row">
            <div class="col">

            </div>
        </div>
    </div>

{% endblock %}